def delta(flag: str, S: float, K: float, t: float, r: float, sigma: float, q: float) -> float: ...
def gamma(flag: str, S: float, K: float, t: float, r: float, sigma: float, q: float) -> float: ...
def theta(flag: str, S: float, K: float, t: float, r: float, sigma: float, q: float) -> float: ...
def vega(flag: str, S: float, K: float, t: float, r: float, sigma: float, q: float) -> float: ...
def rho(flag: str, S: float, K: float, t: float, r: float, sigma: float, q: float) -> float: ...
