from numpy.typing import ArrayLike

def accuracy_score(y_true: ArrayLike, y_pred: ArrayLike) -> float: ...
def mean_absolute_error(y_true: ArrayLike, y_pred: ArrayLike) -> float: ...
def mean_squared_error(y_true: ArrayLike, y_pred: ArrayLike) -> float: ...
def r2_score(y_true: ArrayLike, y_pred: ArrayLike) -> float: ...
def roc_auc_score(y_true: ArrayLike, y_score: ArrayLike) -> float: ...
