"""Conservative, baseline-relative source accounting for the KnK sprint.

The counter is an eligibility gate, not a substitute for reviewing code quality.
Renaming files, copying baseline code, comments and whitespace earn no credit.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import subprocess
import sys
from collections import Counter
from collections.abc import Iterable
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path, PurePosixPath

EXTENSIONS = {".py", ".ts", ".tsx", ".js", ".jsx", ".sql", ".css", ".scss", ".sh", ".ps1"}
EXCLUDED_PARTS = {
    "node_modules",
    "dist",
    "build",
    "coverage",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".git",
    "__pycache__",
    "generated",
    "vendor",
    "fixtures",
    "screenshots",
    "docs",
    "logs",
    "reports",
    "test-results",
    "playwright-report",
    "data",
    ".knk-object-store",
    ".turbo",
}
GATES = {
    "backend": 9000,
    "frontend": 6000,
    "workers_agents_reports_infrastructure": 3000,
    "tests": 7000,
}
GENERATED_MARKERS = (
    "@generated",
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "generated by openapi",
    "generated by prisma",
    "do not edit this generated",
)


@dataclass(frozen=True)
class SourceFile:
    path: str
    category: str
    physical_lines: int
    eligible_lines: tuple[str, ...]
    digest: str


def git(root: Path, *args: str, binary: bool = False) -> str | bytes:
    result = subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True,
        check=True,
    )
    return result.stdout if binary else result.stdout.decode("utf-8", errors="strict")


def category_for(path: str) -> str | None:
    parts = PurePosixPath(path).parts
    lower = tuple(part.lower() for part in parts)
    name = lower[-1] if lower else ""
    if PurePosixPath(name).suffix not in EXTENSIONS:
        return None
    if any(part in EXCLUDED_PARTS or part.startswith((".next", ".venv")) for part in lower):
        return None
    if "public" in lower or name.endswith((".min.js", ".min.css", ".d.ts")):
        return None
    if any(token in name for token in ("lockfile", "schema.generated", "client.generated")):
        return None
    if "api-client" in lower and "generated" in name:
        return None
    if any(part in {"test", "tests", "__tests__"} for part in lower):
        return "tests"
    if name.startswith("test_") or re.search(r"\.(?:test|spec)\.[jt]sx?$", name):
        return "tests"
    if lower[:1] == ("apps",) or lower[:2] in {
        ("packages", "design-system"),
        ("packages", "search"),
        ("packages", "terminal-functions"),
        ("packages", "api-client"),
    }:
        return "frontend"
    if lower[:2] == ("services", "api") and "scripts" not in lower:
        return "backend"
    if lower[:1] in {("packages",), ("migrations",)}:
        return "backend"
    if lower[:1] in {("services",), ("scripts",), ("infrastructure",), ("monitoring",)}:
        return "workers_agents_reports_infrastructure"
    return None


def python_docstring_lines(text: str) -> set[int]:
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return set()
    ignored: set[int] = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            body = node.body
            if body and isinstance(body[0], ast.Expr):
                value = body[0].value
                if isinstance(value, ast.Constant) and isinstance(value.value, str):
                    ignored.update(
                        range(body[0].lineno, (body[0].end_lineno or body[0].lineno) + 1)
                    )
    return ignored


def eligible_lines(path: str, content: str) -> tuple[str, ...]:
    header = [line.strip().lower() for line in content.splitlines()[:20]]
    comments = [line for line in header if line.startswith(("#", "//", "/*", "*", '"""', "'''"))]
    if any(marker in line for line in comments for marker in GENERATED_MARKERS):
        return ()
    suffix = PurePosixPath(path).suffix
    ignored = python_docstring_lines(content) if suffix == ".py" else set()
    hash_comments = suffix in {".py", ".ps1", ".sh"}
    block_comment = False
    result: list[str] = []
    for index, line in enumerate(content.splitlines(), 1):
        value = line.strip()
        if index in ignored or not value:
            continue
        if block_comment:
            if "*/" in value:
                block_comment = False
                value = value.split("*/", 1)[1].strip()
            else:
                continue
        if value.startswith("/*"):
            if "*/" not in value:
                block_comment = True
                continue
            value = value.split("*/", 1)[1].strip()
        if not value or value.startswith("//") or (hash_comments and value.startswith("#")):
            continue
        if suffix == ".sql" and value.startswith("--"):
            continue
        if not any(character.isalnum() for character in value):
            continue
        result.append(" ".join(value.split()))
    return tuple(result)


def make_source(path: str, raw: bytes) -> SourceFile | None:
    category = category_for(path)
    if category is None or b"\x00" in raw:
        return None
    try:
        content = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        return None
    return SourceFile(
        path,
        category,
        len(content.splitlines()),
        eligible_lines(path, content),
        hashlib.sha256(raw).hexdigest(),
    )


def baseline_sources(root: Path, baseline: str) -> list[SourceFile]:
    listed = git(root, "ls-tree", "-r", "--name-only", "-z", baseline)
    assert isinstance(listed, str)
    paths = [path for path in listed.split("\0") if path and category_for(path)]
    sources: list[SourceFile] = []
    for path in paths:
        raw = git(root, "show", f"{baseline}:{path}", binary=True)
        assert isinstance(raw, bytes)
        source = make_source(path, raw)
        if source:
            sources.append(source)
    return sources


def working_sources(root: Path) -> list[SourceFile]:
    listed = git(root, "ls-files", "--cached", "--others", "--exclude-standard", "-z")
    assert isinstance(listed, str)
    result: list[SourceFile] = []
    for path in sorted(set(listed.split("\0")) - {""}):
        if category_for(path) is None:
            continue
        target = root / path
        if target.is_symlink() or not target.is_file():
            continue
        if not target.resolve().is_relative_to(root.resolve()):
            raise ValueError(f"Source path escapes repository: {path}")
        source = make_source(path, target.read_bytes())
        if source:
            result.append(source)
    return result


def totals(sources: Iterable[SourceFile]) -> dict[str, dict[str, int]]:
    result = {
        category: {"files": 0, "physical_lines": 0, "eligible_lines": 0} for category in GATES
    }
    for source in sources:
        group = result[source.category]
        group["files"] += 1
        group["physical_lines"] += source.physical_lines
        group["eligible_lines"] += len(source.eligible_lines)
    return result


def delta(baseline: list[SourceFile], current: list[SourceFile]) -> dict[str, object]:
    previous = {source.path: source for source in baseline}
    old_pool: Counter[str] = Counter(line for source in baseline for line in source.eligible_lines)
    new_pool: Counter[str] = Counter(line for source in current for line in source.eligible_lines)
    # Credit a novel normalized line once; repeated boilerplate earns no extra LOC.
    novel = Counter({line: 1 for line in new_pool if line not in old_pool})
    credited: dict[str, int] = dict.fromkeys(GATES, 0)
    files: list[dict[str, object]] = []
    for source in sorted(current, key=lambda item: item.path):
        old = previous.get(source.path)
        old_lines = Counter(old.eligible_lines if old else ())
        candidates = Counter(source.eligible_lines) - old_lines
        count = 0
        for line, occurrences in candidates.items():
            accepted = min(occurrences, novel[line])
            count += accepted
            novel[line] -= accepted
        credited[source.category] += count
        if count or (old and source.digest != old.digest) or old is None:
            files.append(
                {
                    "path": source.path,
                    "category": source.category,
                    "qualifying_added": count,
                    "physical_lines": source.physical_lines,
                    "over_1200_lines": source.physical_lines > 1200,
                }
            )
    gates = {
        category: {
            "added": credited[category],
            "minimum": minimum,
            "passed": credited[category] >= minimum,
        }
        for category, minimum in GATES.items()
    }
    total = sum(credited.values())
    return {
        "categories": gates,
        "total": total,
        "minimum_total": 25000,
        "line_gates_passed": total >= 25000 and all(item["passed"] for item in gates.values()),
        "semantic_review_required": True,
        "files": files,
        "baseline_inventory": totals(baseline),
        "current_inventory": totals(current),
    }


def source_inventory(root: Path, baseline: str, sources: list[SourceFile]) -> dict[str, object]:
    endpoints: list[dict[str, object]] = []
    large_files = []
    for source in sources:
        if source.physical_lines > 1200:
            large_files.append({"path": source.path, "lines": source.physical_lines})
        if source.category != "backend" or not source.path.endswith(".py"):
            continue
        text = git(root, "show", f"{baseline}:{source.path}")
        assert isinstance(text, str)
        tree = ast.parse(text)
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for decorator in node.decorator_list:
                if not isinstance(decorator, ast.Call) or not isinstance(
                    decorator.func, ast.Attribute
                ):
                    continue
                if (
                    decorator.func.attr not in {"get", "post", "put", "patch", "delete"}
                    or not decorator.args
                ):
                    continue
                route = decorator.args[0]
                if isinstance(route, ast.Constant) and isinstance(route.value, str):
                    endpoints.append(
                        {
                            "file": source.path,
                            "line": node.lineno,
                            "method": decorator.func.attr.upper(),
                            "router_path": route.value,
                        }
                    )
    registry = git(root, "show", f"{baseline}:services/api/app/data/functions.json")
    assert isinstance(registry, str)
    functions = json.loads(registry)
    return {
        "baseline": baseline,
        "categories": totals(sources),
        "frontend_registry": functions,
        "route_patterns": sorted({item["route"] for item in functions}),
        "endpoint_declarations": endpoints,
        "existing_files_over_1200": large_files,
        "test_files": [source.path for source in sources if source.category == "tests"],
        "source_files": [
            {key: value for key, value in asdict(source).items() if key != "eligible_lines"}
            for source in sources
        ],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--baseline")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--inventory", action="store_true")
    parser.add_argument("--check", action="store_true", help="Exit 1 when any LOC gate is unmet")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    baseline = args.baseline or (root / ".knk-25k-baseline").read_text(encoding="ascii").strip()
    if not re.fullmatch(r"[0-9a-f]{40}", baseline):
        parser.error("Baseline must be a full 40-character commit hash")
    git(root, "cat-file", "-e", f"{baseline}^{{commit}}")
    old = baseline_sources(root, baseline)
    report = (
        source_inventory(root, baseline, old)
        if args.inventory
        else delta(old, working_sources(root))
    )
    report.update(
        {
            "baseline": baseline,
            "commit": str(git(root, "rev-parse", "HEAD")).strip(),
            "branch": str(git(root, "branch", "--show-current")).strip(),
            "date": datetime.now(UTC).isoformat(),
        }
    )
    rendered = json.dumps(report, indent=2, sort_keys=True)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered + "\n", encoding="utf-8")
    summary = {
        key: value
        for key, value in report.items()
        if key
        not in {
            "files",
            "frontend_registry",
            "endpoint_declarations",
            "source_files",
            "test_files",
            "route_patterns",
        }
    }
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 1 if args.check and not report.get("line_gates_passed", False) else 0


if __name__ == "__main__":
    sys.exit(main())
